### ISSUE TITLE
Could not decode code repo credentials

### ISSUE THREAD

**Issue by agardnerIT** [keptn-sandbox/keptn-gitops-operator#30]
Full steps:

```
export GITOPS_VERSION=0.1.0-pre.5

# Download and install Keptn GitOps secret helper
wget https://github.com/keptn-sandbox/keptn-gitops-operator/releases/download/$GITOPS_VERSION/keptn-gitops-secrets-linux-amd64
mv keptn-gitops-secrets-linux-amd64 /usr/bin/keptnsecrets && chmod +x /usr/bin/keptnsecrets
mkdir keptnsecrets

# Generate keys
keptnsecrets generate-keys -f keptnsecrets/keptnkeys

# RSA Encrypt Git PAT Token and Private Key
export RSA_GIT_TOKEN=$(keptnsecrets encrypt -p keptnsecrets/keptnkeys.pub -s ghp_********)
export RSA_PRIVATE_KEY=$(cat keptnsecrets/keptnkeys.priv)

# Trying to spin up control plane on localhost
# Omit everything related to remote execution planes
kubectl apply -f https://github.com/keptn-sandbox/keptn-gitops-operator/releases/download/$GITOPS_VERSION/keptn-operator_crd.yaml
kubectl apply -f https://github.com/keptn-sandbox/keptn-gitops-operator/releases/download/$GITOPS_VERSION/gitops-operator_crd.yaml
helm upgrade --install --create-namespace --atomic -n keptn keptn-gitops \
  https://github.com/keptn-sandbox/keptn-gitops-operator/releases/download/$GITOPS_VERSION/keptn-gitops-$GITOPS_VERSION.tgz \
  --set global.rsaSecret.privateBase64="$RSA_PRIVATE_KEY"

# Create KeptnGitRepository YAML
cat <<EOF > kgr.yaml
apiVersion: "keptn.sh/v1"
kind: "KeptnGitRepository"
metadata:
  name: "keptn-ca-demo"
spec:
  repository: "https://github.com/agardnerIT/keptn-gitops"
  username: agardnerit
  password: "rsa:$RSA_GIT_TOKEN"
  branch: main
EOF

# Apply
kubectl -n keptn apply -f kgr.yaml
# keptngitrepository.keptn.sh/keptn-ca-demo created

# View Logs
kubectl -n keptn logs -l control-plane=gitops-operator --all-containers --tail 100 --follow
```

Error is:
```
1.6475784772424371e+09  ERROR   controller.keptngitrepository   Reconciler error        {"reconciler group": "keptn.sh", "reconciler kind": "KeptnGitRepository", "name": "keptn-ca-demo", "namespace": "keptn", "error": "illegal base64 data at input byte 0"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
1.6475794772437243e+09  INFO    controllers.KeptnGitRepository  Reconciling KeptnGitRepository
1.647579477243837e+09   INFO    controllers.KeptnGitRepository  Syncing {"url": "https://github.com/agardnerIT/keptn-gitops"}
1.647579477243851e+09   INFO    controllers.KeptnGitRepository  Syncing {"status": {}}
1.6475794772441401e+09  ERROR   controllers.KeptnGitRepository  Could not decode code repo credentials  {"URI": "https://github.com/agardnerIT/keptn-gitops", "error": "illegal base64 data at input byte 0"}
```

**Comment by thschue** [comment]
Hello Adam, and thank you for trying this out. The operator expects the private key to be base64 encoded, so 

```
export RSA_PRIVATE_KEY=$(cat keptnsecrets/keptnkeys.priv | base64)
helm upgrade --install --create-namespace --atomic -n keptn keptn-gitops \
  https://github.com/keptn-sandbox/keptn-gitops-operator/releases/download/$GITOPS_VERSION/keptn-gitops-$GITOPS_VERSION.tgz \
  --set global.rsaSecret.privateBase64="$RSA_PRIVATE_KEY"
```

should do the job

**Comment by agardnerIT** [comment]
Excellent, I'm a little further now. 

```
# This goes in Instance.yaml
export RSA_KEPTN_API_TOKEN=$(keptnsecrets encrypt -p keptnsecrets/keptnkeys.pub -s <KEPTN_API_TOKEN> | base64)
# This goes in project1.yaml
export RSA_GIT_TOKEN=$(keptnsecrets encrypt -p keptnsecrets/keptnkeys.pub -s <GIT_PAT_TOKEN> | base64)

apiVersion: "keptn.sh/v1"
kind: "KeptnInstance"
metadata:
  name: "mykeptn"
spec:
  apiUrl: "http://localhost/api"
  tokenType: "x-token"
  apiToken: "rsa:$RSA_KEPTN_API_TOKEN"


apiVersion: "keptn.sh/v1"
kind: "KeptnProject"
metadata:
  name: "project1"
spec:
  repository: "https://github.com/agardnerIT/keptn-gitops-project1"
  username: "agardnerit"
  password: "rsa:$RSA_GIT_TOKEN"
```

Error:
```
 Reconciling Project     {"Request.Namespace": "keptn", "Request.Name": "project1"}
1.6475842164425836e+09  ERROR   Could not get Keptn Instance    {"Request.Namespace": "keptn", "Request.Name": "project1", "error": "could not fetch keptn instance: KeptnInstance.keptn.sh \"default\" not found"}
```
