### ISSUE TITLE
Stages not created AND automatic stages created

### ISSUE THREAD

**Issue by agardnerIT** [keptn-sandbox/keptn-gitops-operator#35]
This ticket is most likely a "misunderstanding" ticket from a newbie but showing my working / thinking here so it may inform further enhancements  / docs.

I've onboarded `project1` and I automatically see 3 stages: `dev`, `hardening` and `production`. I didn't apply these stages and they don't exist in my Git repo so the operator is creating them automatically. To my (extremely limited) understanding of GitOps, this is against the paradigm as my repo should be the source of truth and thus I now have stages that **do not** appear in my repo.

I believe this is done because creating a keptn project without stages is not currently possible.

Perhaps I'm forced down this workflow because I'm using GitHub.com and modifying one file at a time rather than committing everything at once. Even so, this is, IMO, how most beginners would probably approach things.

Nevertheless, I create a `.keptn/stage.yaml` file (side note, is this name hardcoded? I'd like to call this `stages.yaml` instead):

```
---
apiVersion: "keptn.sh/v1"
kind: "KeptnStage"
metadata:
  name: "foostage"
spec:
  project: "project1"
```

and my stage isn't created. In my Git upstream I see a `shipyard.yaml` file has been created for me so perhaps that is overriding the gitops operator:

```
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "podtato-head"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "dummy"
          tasks:
            - name: "dummy"
    - name: "hardening"
      sequences:
        - name: "dummy"
          tasks:
            - name: "dummy"
    - name: "production"
      sequences:
        - name: "dummy"
          tasks:
            - name: "dummy"
```

This thread may lead to Keptn RFEs but the workflow that would work for me (and IMHO is the "most logical" esp. to a new user is):

```
1. Install operators
2. Create `instance.yaml`
3. Create `project.yaml` (this is an empty project without stages)
4. Create `stages.yaml` (creates an empty stage without sequences)
5. Create `sequences.yaml` with one or more sequences and tasks
6. Modify `stages.yaml` to link sequences
```
