### ISSUE TITLE
Extend the operator to support "DeploymentURIsLocal" and "DeploymentURIsPublic"

### ISSUE THREAD

**Issue by didiladi** [keptn-sandbox/keptn-gitops-operator#7]
Currently, a deployment triggered with the operator does not include any information how the deployed service is exposed. Keptn usually uses the `DeploymentURIsLocal` and `DeploymentURIsLocal` properties in the `sh.keptn.event.deployment.finished` event to pass along this information.

In our case, the keptn helm service uses the following code to set this information: https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/helm-service/controller/deployment_handler.go#L221. It is set based on the infromation provided in the `sh.keptn.event.[STAGENAME].delivery.triggered` event.

This means, that the operator needs to provide this information when triggering the deployment via a `sh.keptn.event.[STAGENAME].delivery.triggered` event.

Event data: https://github.com/keptn/go-utils/blob/master/pkg/lib/v0_2_0/deployment.go

**Comment by didiladi** [comment]
I'm planning to extend the `metadata.yaml` file with the following options:

E.g.:
```
metadata:
  imageVersion: 0.0.1
  deploymentURIsLocal:
    - http://<deployment-name>.<namespace>.svc.cluster.local
  deploymentURIsPublic:
    - http://example.com/my-service
```

Is that ok for you @thschue?
